version: 2
defaults:
  working_directory: /tmp
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.10.0
    steps:
      - checkout
      - run:
          name: Make build directory
          command: mkdir -p /tmp/workspace/code
      - run:
          name: Copy all to the workspace directory
          command: cp -r * /tmp/workspace/code
      - run:
          name: list files
          command: cd /tmp/workspace/code && ls
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - code/*
  deploy:
    docker:
      - image: google/cloud-sdk
        environment:
          STORAGE_BUCKET: testkeerthu
    steps:
      - attach_workspace:
          at: /tmp/workspace
      # - run:
      #     name: Initialize gcloud
      #     command: /tmp/workspace/code/authgcloud.sh
      # - run:
      #     name: json file
      #     command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      # - run:
      #     name: config initialize
      #     command: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      # - run:
      #     name: config initialize
      #     command: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: list files
          command: ls /tmp/workspace/code
      # - run:
      #     name: deploy
      #     command: /tmp/workspace/code/deploy.sh
      - run:
          name: start copying
          command: echo "Copying build to Storage"
      - run:
          name: Folder Access
          command: gsutil defacl ch -u AllUsers:READER gs://$STORAGE_BUCKET
      - run:
          name: Compress the contents
          command: tar -czvf /tmp/workspace/code.tar.gz /tmp/workspace/code/*
      - run:
          name: Copy contents
          command: gsutil rsync -R /tmp/workspace/code.tar.gz gs://$STORAGE_BUCKET
      - run:
          name: list the contents
          command: ls /tmp/workspace
      - run:
          name: print copying
          command: echo "Copying Completed"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
